{% set name = "circuits" %}
{% set version = "3.2.2" %}
{% set sha256 = "ce069ef42c02299a485e6871b19d7cddc9ed36f0e018869a09ad53b734d0044e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.0
    - pip
    - setuptools_scm
  run:
    - python >=3.0
    - setuptools

test:
  imports:
    - circuits

about:
  home: http://circuitsframework.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: circuits is a Lightweight Event driven and Asynchronous Application Framework for the Python Programming Language with a strong Component Architecture

extra:
  recipe-maintainers:
    - daniel88ferreira
    - abloemert
