travis:
  secure:
    BINSTAR_TOKEN: bkOKeC4xachRoqlTLnjOx/7Xo9yoxbusjd8JoZPJQXL1IEShqV8WXL8FXM2oKMBM6SU+LzclywifFdf7W495XM7B9lkxQ47NVSID7LbuQ8Ewyedd8nZ4GfgGgte/hNta1Ky4S1+WwF24CuEdHUYVmOK01T8bjERxmMwvZowTxaDV25MRqM5iQ+QCoTU25VzXKD2ix92kJ5XUgYYC+Mcc8AiTwxIYsz4ziqXnl5LP7r93EY8p0F6KmHxmk6Or66YKv+xxKK1O2qh3yfUr+GEdqWsX+6Yy40Qy9Lg1zWsubTDtxcd2/7WB/x/MFyUF8Ka1Zvz5xIyzJFmTU5LRQICKMHk+8c76DaLZtBOKTkJ+qlPj9i+NduDljNqlV3yNfX6Gk7QrGuLz4eUfepDe7Df9VnwdxkA8lrD+qVzzCkTIQC5BmVIMX+qqKSYYMsK+LsFgpqy1KpXxhhNY4q+t6XVL0i+nJNoNJ8ShyjZdL4V8mNN4CvJBeuMC/zBtpLCjDpHghMf0VcE1khuyZg4RuBxXUjuvPIoCOXiI6hULKZBahTNXit6EoD17BRV2GE2ebwbTZWl4vj2LR0+IWJWhUAkRH8FoN3JE1jpFXHr7Ld5B/xy0MWKJrShKXa6irNU3q6SdDSpP51M5fE7Rk6/ed1bkbPLIYM6wggDCT9yMrK9tVec=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
